# Load packages
library(dplyr)
library(Seurat)
library(patchwork)
library(hdf5r)
library(clustree)
library(celldex)
library(SingleR)
library(decoupleR)
library(pheatmap)
library(tibble)
library(tidyr)
library(OmnipathR)